// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpE5CYeSHysQsyiu2d2iX1MxR7CEI0Ujw',
    appId: '1:237528939048:web:50c8b1331210eedc0ed31d',
    messagingSenderId: '237528939048',
    projectId: 'e-ecommerce-f3bee',
    authDomain: 'e-ecommerce-f3bee.firebaseapp.com',
    storageBucket: 'e-ecommerce-f3bee.appspot.com',
    measurementId: 'G-4XECPBYT41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4YAlJdb6Wj0V2kAJKnXgk0_pBVYQ20uI',
    appId: '1:237528939048:android:ccc6c672d5f160690ed31d',
    messagingSenderId: '237528939048',
    projectId: 'e-ecommerce-f3bee',
    storageBucket: 'e-ecommerce-f3bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz_E5niJk-i7ZT1ss_90c-IF3WUT5jFko',
    appId: '1:237528939048:ios:4610b2a43f7876190ed31d',
    messagingSenderId: '237528939048',
    projectId: 'e-ecommerce-f3bee',
    storageBucket: 'e-ecommerce-f3bee.appspot.com',
    androidClientId:
        '237528939048-pmnhtgg71326h1836flk2d72vvmjgi6o.apps.googleusercontent.com',
    iosClientId:
        '237528939048-7ofa9fe44lqn1lioioe656rhna01rguu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz_E5niJk-i7ZT1ss_90c-IF3WUT5jFko',
    appId: '1:237528939048:ios:4610b2a43f7876190ed31d',
    messagingSenderId: '237528939048',
    projectId: 'e-ecommerce-f3bee',
    storageBucket: 'e-ecommerce-f3bee.appspot.com',
    androidClientId:
        '237528939048-pmnhtgg71326h1836flk2d72vvmjgi6o.apps.googleusercontent.com',
    iosClientId:
        '237528939048-7ofa9fe44lqn1lioioe656rhna01rguu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpE5CYeSHysQsyiu2d2iX1MxR7CEI0Ujw',
    appId: '1:237528939048:web:ef085cc9f02a02990ed31d',
    messagingSenderId: '237528939048',
    projectId: 'e-ecommerce-f3bee',
    authDomain: 'e-ecommerce-f3bee.firebaseapp.com',
    storageBucket: 'e-ecommerce-f3bee.appspot.com',
    measurementId: 'G-H1GFE7GQ2K',
  );
}
